apiVersion: apps/v1
kind: Deployment
metadata:
  name: viz-service
  namespace: synodic
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation-worker
  namespace: synodic
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: synodic
spec:
  replicas: 1
