apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: viz-service
  namespace: synodic
  labels:
    app.kubernetes.io/name: viz-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: viz-service
