apiVersion: v1
kind: ServiceAccount
metadata:
  name: synodic-backend
  namespace: synodic
  annotations:
    # For Workload Identity, set:
    # iam.gke.io/gcp-service-account: synodic-backend@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: synodic
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: synodic-infra
  namespace: synodic
