"""The quickstart seed database must not ship credential material.

``data/quickstart/nexus_core.db`` is baked into the quickstart image
(``backend/Dockerfile.viz-quickstart``) and is tracked in git on purpose --
it carries the demo graph, views and workspaces that make the quickstart
worth running.

It also used to carry four user rows with real Argon2id password hashes and
two live reset-token hashes. One of them, ``admin@synodic.local``, is a
platform admin that QUICKSTART.md never mentions: the documented login is
the bootstrap admin ``admin@nexuslineage.local``, created at first run. So
every quickstart image shipped a second, undocumented admin account whose
password hash was public in the repository.

The rows stay -- they are demo data and other tables carry FKs to them --
but their credentials are cleared. This test exists because the seed is
regenerated by hand from a developer's local stack, which is exactly how
the hashes got in there the first time.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest

from backend.auth_service.core.password import is_password_set

SEED = Path(__file__).resolve().parents[2] / "data" / "quickstart" / "nexus_core.db"


@pytest.fixture(scope="module")
def seed_users() -> list[sqlite3.Row]:
    if not SEED.exists():  # pragma: no cover - the file is tracked
        pytest.skip(f"quickstart seed not present at {SEED}")
    db = sqlite3.connect(f"file:{SEED}?mode=ro", uri=True)
    db.row_factory = sqlite3.Row
    try:
        return db.execute("select * from users").fetchall()
    finally:
        db.close()


def test_the_seed_actually_has_users_to_check(seed_users):
    """Guards the guard: an empty table would make every assertion below
    pass without testing anything."""
    assert len(seed_users) > 0


def test_no_seeded_account_can_be_signed_into_with_a_password(seed_users):
    """``is_password_set`` is the same predicate the login path uses, so
    this asserts the property that matters rather than a string shape."""
    offenders = [
        row["email"] for row in seed_users
        if is_password_set(row["password_hash"])
    ]
    assert offenders == [], (
        f"{offenders} ship a usable password hash in the quickstart image. "
        "Clear it to the disabled-password sentinel before committing a "
        "regenerated seed."
    )


def test_no_seeded_account_carries_a_live_reset_token(seed_users):
    """A reset-token hash is a credential too: whoever holds the matching
    plaintext can take the account over without knowing the password."""
    offenders = [
        row["email"] for row in seed_users
        if row["reset_token_hash"] or row["reset_token_expires_at"]
    ]
    assert offenders == [], (
        f"{offenders} ship a pending password-reset token in the quickstart "
        "image."
    )
