apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: graph-service-backendconfig
  namespace: synodic
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 8001
  timeoutSec: 120
  connectionDraining:
    drainingTimeoutSec: 15
