apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: graph-service
  namespace: synodic
  labels:
    app.kubernetes.io/name: graph-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: graph-service
