apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/replicas.yaml
  - path: patches/resource-limits.yaml
  - path: patches/ingress-patch.yaml

images:
  - name: REGISTRY/viz-service
    newName: gcr.io/PROJECT_ID/viz-service
    newTag: staging-latest
  - name: REGISTRY/aggregation-controlplane
    newName: gcr.io/PROJECT_ID/aggregation-controlplane
    newTag: staging-latest
  - name: REGISTRY/aggregation-worker
    newName: gcr.io/PROJECT_ID/aggregation-worker
    newTag: staging-latest
  - name: REGISTRY/stats-service
    newName: gcr.io/PROJECT_ID/stats-service
    newTag: staging-latest
  - name: REGISTRY/frontend
    newName: gcr.io/PROJECT_ID/frontend
    newTag: staging-latest
  - name: REGISTRY/falkordb
    newName: gcr.io/PROJECT_ID/falkordb
    newTag: staging-latest
  - name: REGISTRY/seed
    newName: gcr.io/PROJECT_ID/seed
    newTag: staging-latest
