apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/replicas.yaml
  - path: patches/resource-limits.yaml
  - path: patches/ingress-patch.yaml

images:
  - name: REGISTRY/synodic-viz
    newName: gcr.io/PROJECT_ID/synodic-viz
    newTag: staging-latest
  - name: REGISTRY/synodic-controlplane
    newName: gcr.io/PROJECT_ID/synodic-controlplane
    newTag: staging-latest
  - name: REGISTRY/synodic-worker
    newName: gcr.io/PROJECT_ID/synodic-worker
    newTag: staging-latest
  - name: REGISTRY/synodic-graph
    newName: gcr.io/PROJECT_ID/synodic-graph
    newTag: staging-latest
  - name: REGISTRY/synodic-frontend
    newName: gcr.io/PROJECT_ID/synodic-frontend
    newTag: staging-latest
  - name: REGISTRY/synodic-falkordb
    newName: gcr.io/PROJECT_ID/synodic-falkordb
    newTag: staging-latest
  - name: REGISTRY/synodic-seed
    newName: gcr.io/PROJECT_ID/synodic-seed
    newTag: staging-latest
