$patch: delete
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: synodic
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: synodic
---
$patch: delete
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: synodic
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: synodic
