apiVersion: apps/v1
kind: Deployment
metadata:
  name: viz-service
  namespace: synodic
spec:
  template:
    spec:
      containers:
        - name: viz-service
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation-controlplane
  namespace: synodic
spec:
  template:
    spec:
      containers:
        - name: controlplane
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 768Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation-worker
  namespace: synodic
spec:
  template:
    spec:
      containers:
        - name: worker
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: synodic
spec:
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
