apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aggregation-controlplane
  namespace: synodic
  labels:
    app.kubernetes.io/name: aggregation-controlplane
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aggregation-controlplane
