apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synodic-ingress
spec:
  rules:
    - host: synodic.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: synodic-certificate
spec:
  domains:
    - synodic.example.com
