apiVersion: apps/v1
kind: Deployment
metadata:
  name: viz-service
spec:
  template:
    spec:
      containers:
        - name: viz-service
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation-controlplane
spec:
  template:
    spec:
      containers:
        - name: controlplane
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation-worker
spec:
  template:
    spec:
      containers:
        - name: worker
          resources:
            requests:
              cpu: "1"
              memory: 1Gi
            limits:
              cpu: "4"
              memory: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-service
spec:
  template:
    spec:
      containers:
        - name: graph-service
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
