apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: synodic
type: Opaque
stringData:
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
  CREDENTIAL_ENCRYPTION_KEY: "${CREDENTIAL_ENCRYPTION_KEY}"
  ADMIN_EMAIL: "${ADMIN_EMAIL}"
  ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
